[build]
; git tag or branch of SBCL to build (see Containerfile SBCL_VERSION build arg)
SBCL_VERSION=master
; git tag or branch of coalton/mine to clone (see Containerfile COALTON_VERSION build arg)
COALTON_VERSION=main
